// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Feed struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Name          string
	Url           string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	LastFetchedAt sql.NullTime
	Description   sql.NullString
	ImageUrl      sql.NullString
}

type FeedFollow struct {
	ID        uuid.UUID
	FeedID    uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Post struct {
	ID           uuid.UUID
	FeedID       uuid.UUID
	Title        string
	Url          string
	Description  sql.NullString
	PublishedAt  sql.NullTime
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Guid         sql.NullString
	Author       sql.NullString
	ThumbnailUrl sql.NullString
}

type User struct {
	ID        uuid.UUID
	Name      string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
	ApiKey    string
}
