// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: posts.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one


INSERT INTO posts (
    id, 
    feed_id, 
    title, 
    url, 
    description, 
    author,
    thumbnail_url,
    published_at, 
    guid,
    created_at, 
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, feed_id, title, url, description, published_at, created_at, updated_at, guid, author, thumbnail_url
`

type CreatePostParams struct {
	ID           uuid.UUID
	FeedID       uuid.UUID
	Title        string
	Url          string
	Description  sql.NullString
	Author       sql.NullString
	ThumbnailUrl sql.NullString
	PublishedAt  sql.NullTime
	Guid         sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// -- name: GetNextFeedToFetch :many
// SELECT * FROM feeds
// ORDER BY last_fetched_at ASC NULLS FIRST
// LIMIT $1;
// -- name: MarkFeedAsFetched :exec
// UPDATE feeds
// SET last_fetched_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
// WHERE id = $1;
func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.ID,
		arg.FeedID,
		arg.Title,
		arg.Url,
		arg.Description,
		arg.Author,
		arg.ThumbnailUrl,
		arg.PublishedAt,
		arg.Guid,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Guid,
		&i.Author,
		&i.ThumbnailUrl,
	)
	return i, err
}

const getPostsForUser = `-- name: GetPostsForUser :many

SELECT posts.id, posts.feed_id, posts.title, posts.url, posts.description, posts.published_at, posts.created_at, posts.updated_at, posts.guid, posts.author, posts.thumbnail_url FROM posts
JOIN feed_follows ON feed_follows.feed_id = posts.feed_id
WHERE feed_follows.user_id = $1
ORDER BY posts.published_at DESC
LIMIT $2
`

type GetPostsForUserParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) GetPostsForUser(ctx context.Context, arg GetPostsForUserParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getPostsForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Guid,
			&i.Author,
			&i.ThumbnailUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
